OzoneUI/Controllers/StateViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ozone.BAL;
using OzoneUI.Models;
using Ozone.DAL;
using System.Web.Script.Serialization;
using Newtonsoft.Json;


namespace OzoneUI.Controllers
{
    public class StateViewController : Controller
    {
        //
        // GET: /StateView/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(long Stateid = 0)
        {
            if (Stateid != null)
            {
                StateModels state = new StateModels();
                state.lstCountry = new CountryBAL().DDLCountry();

                if (Stateid > 0)
                {
                    STATE_MASTER balState = new StateBAL().GetStateById(Stateid);
                    state.Pk_State_Id = Stateid;
                    state.State_Name = balState.State_Name;
                    state.State_Code = balState.State_Code;
                    state.Fk_Country_Id = balState.Fk_Country_Id;
                    return PartialView(state);
                }
                else
                {
                    return PartialView(state);
                }
            }
            else
            {
                return PartialView();

            }

        }

        public ContentResult GetState(int? start, int length,string search)
        {
            int iDisplayStart = start == null ? 0 : start.Value;

            var obj = new StateBAL().ListState(iDisplayStart, length,search);
            var total = new StateBAL().GetStateCount(search);

            DatatablePaggeing d = new DatatablePaggeing();
            d.aaData = obj;
            d.iTotalDisplayRecords = total;
            d.iTotalRecords = total;
            d.sEcho = "";

            var list = JsonConvert.SerializeObject(d,
            Formatting.None,
            new JsonSerializerSettings()
            {
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
            });

            return Content(list, "application/json");
            //return new JsonResult { Data = d, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult Edit(long Stateid)
        {
            return PartialView(new StateBAL().GetStateById(Stateid));
        }

        public ContentResult Delete(string id)
        {
            string suc;
            suc = new StateBAL().DeleteState(Convert.ToInt64(id));
            if (suc == "Deleted")
            {
                //return new JsonResult { Data = new { status = true, message = "Product deleted successfully" } };
                return Content("State deleted successfully", "application/text");
            }
            else
            {
                //return new JsonResult { Data = new { status = false, message = "Oops!! Some error occured" } };
                return Content("Oops!! Some error occured", "application/text");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveState(StateBAL State)
        {

            try
            {

                string suc;
                if (new StateBAL().GetStateCount(State.State_Name) > 0)
                {

                    suc = "Exist";
                }
                else
                {
                    if (State.Pk_State_Id > 0)
                    {
                        suc = new StateBAL().EditState(State);
                    }
                    else
                    {
                        suc = StateBAL.InsertState(State);
                    }
                }
                
                if (suc == "Success")
                {
                    return new JsonResult { Data = new { status = true, message = "State added successfully" } };
                }
                else if (suc == "Updated")
                {
                    return new JsonResult { Data = new { status = true, message = "State Updated Successfully" } };
                }
                else if (suc == "Exist")
                {
                    return new JsonResult { Data = new { status = false, message = "State Already Exist" } };
                }
                else
                {
                    return new JsonResult { Data = new { status = false, message = "Oops!! Some error occured" } };
                }

            }
            catch (Exception e)
            {
                return new JsonResult { Data = new { status = false, message = e.Message } };
            }
        }


    }
}

OzoneUI/Views/StateView/Create.cshtml
@model OzoneUI.Models.StateModels

@{
    ViewBag.Title = "Create State";
}


<div>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">State Master</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">

                        @using (Html.BeginForm("SaveState", "StateView", FormMethod.Post, new { role = "form", id = "saveForm" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="panel-body">

                                @Html.ValidationSummary(true)

                                @Html.HiddenFor(model => model.Pk_State_Id)
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Fk_Country_Id, new { @class = "col-md-4 control-label" })
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.Fk_Country_Id, new SelectList(Model.lstCountry, "Pk_Country_Id", "Country_Name"), "--Select ...", new { @class = "form-control select", data_live_search = "true" })
                                        <span class="help-block">@Html.ValidationMessageFor(model => model.Fk_Country_Id)  </span>
                                    </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.State_Name, new { @class = "col-md-4 control-label" })
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(model => model.State_Name, new { @class = "form-control" })
                                            <span class="help-block"> @Html.ValidationMessageFor(model => model.State_Name)</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.State_Code, new { @class = "col-md-4 control-label" })
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(model => model.State_Code, new { @class = "form-control" })
                                            <span class="help-block"> @Html.ValidationMessageFor(model => model.State_Code)</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-6"></div>
                                        <div class="col-md-6">

                                            <button type="submit" id="savebutton" class="btn btn-info mb-control">Submit</button>
                                        </div>
                                    </div>
                                </div>
                        }
                        <div id="msg" style="color:red"></div>

                        @*<div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>*@
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $("#savebutton").button();
    $("body").unbind().on('submit', '#saveForm', function (e) {
        
        e.preventDefault();
        SaveState();
    });

    function SaveState() {
        $('#savebutton').button('loading');
        
        //Validation
        if ($('#State_Name').val().trim() == '' ||
            $('#State_Code').val().trim() == '') {
            $('#msg').html('<div class="failed">All fields are required.</div>');
            $('#savebutton').button('reset');
            return false;
        }

        var State = {
            Fk_Country_Id: $('#Fk_Country_Id').val(),
            State_Name: $('#State_Name').val().trim(),
            State_Code: $('#State_Code').val().trim(),
            Pk_State_Id: $('#Pk_State_Id').val() == '' ? '0' : $('#Pk_State_Id').val()

        };
        //Add validation token
        State.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        //Save Contact
        $.ajax({
            url: '/StateView/SaveState',
            type: 'POST',
            data: State,
            dataType: 'json',
            success: function (data) {
                $('#savebutton').button('reset');
                
              
                if (data.status) {
                    ModalResponce(data.message, true);
                }
                else {
                    ModalResponce(data.message, false);
                }
                //if (data.status) {
                //    $('#ContactID').val('');
                //    $('#ContactPerson').val('');
                //    $('#ContactNo').val('');
                //    $('#StateID').val('');
                //    $('#StateID').val('');
                //    LoadContacts();
                //    $dialog.dialog('close');
                //}
            },
            error: function () {
                $('#savebutton').button('reset');
                
                $('#msg').html('<div class="failed">Error! Please try again.</div>');
            }
        });
    }
</script>

OzoneUI/Views/StateView/Index.cshtml
@model  IEnumerable<Ozone.DAL.STATE_MASTER>


    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

    @Scripts.Render("~/bundles/notify")

    @*<ul class="breadcrumb">
        <li><a href="#">Home</a></li>

        <li class="active">State</li>
        <li>Welcome : <label id="lblUser"></label></li>

    </ul>*@

    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">
                <br />
                <p>
                    <input type="button" class="btn btn-info mb-control" value="Add new State" onclick="CreateState()" />

                </p>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">List of State</h3>
                        <ul class="panel-controls">

                            <li><input id="txtSeach" type="text" class="form-control" name="name" value="" onchange="SearchText(this.value);" placeholder="Search... " /></li>
                        </ul>
                        @*<ul class="panel-controls">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                        </ul>*@
                    </div>
                    <div id='OpenDilog' class="modal" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">

                    </div>

                    <div class="panel-body">
                        <table id="State" class="table ">
                            <thead><tr><th>Country</th><th>State</th><th>State Code</th><th>Action</th></tr></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#lblUserId').text(@Request.QueryString["id"]);
            GetStateJSON();
        });
        function SearchText(srch) {
            GetStateJSON();
        }
        function GetStateJSON() {
            $('#State').dataTable({
                "bDestroy": true
            }).fnDestroy();
            var search = $('#txtSeach').val();
            window.table = $('#State').DataTable({
                "processing": true,
                "serverSide": true,
                'searching': false,
                'language': {
                    "processing": "<img src='../img/loaders/default.gif' />" //add a loading image,simply putting <img src="loader.gif" /> tag.
                },
                "bSort": false,
                "ajax": "/StateView/GetState?search=" + search ,
                "columns": [
                    { "data": "COUNTRY_MASTER.Country_Name" },
                    { "data": "State_Name" },
                    { "data": "State_Code" },
                    { "data": "" }

                ],
                "columnDefs": [{
                    "targets": -1,
                    "data": null,
                    "defaultContent": "<button id='edt' class='btn btn-default btn-rounded btn-sm' ><span class='fa fa-pencil'></span></button>&nbsp;&nbsp;<button id='del' class='btn btn-default btn-rounded btn-sm edit'><span class='fa fa-times'></span></button>"
                }],
                "bDestroy": true


            });
            $('#State th:first').removeClass('sorting_asc');
            $('#State tbody').unbind().on('click', 'button', function () {

                var data = window.table.row($(this).parents('tr')).data();
                if ($(this).attr('id') == 'edt') {

                    EditState(data.Pk_State_Id);
                }
                if ($(this).attr('id') == 'del') {
                    DeleteState(data.Pk_State_Id);
                }


            });
        }
        $(".panel-refresh").on("click", function () {
            window.table.ajax.reload();
        });
        function ModalResponce(data, suc) {

            if (suc) {
                $("#OpenDilog").modal('hide');
                noty({ text: data, layout: 'topRight', type: 'success' }).setTimeout(3000);;

            }
            else {
                $("#OpenDilog").modal('hide');
                noty({ text: data, layout: 'topRight', type: 'error' }).setTimeout(3000);;
            }
            window.table.ajax.reload();
        }
        function EditState(B_ID) {

            var div = $("#OpenDilog");
            $.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
            div.load("/StateView/Create?Stateid=" + B_ID, function () {
                $.mpb("update", {
                    value: 100, speed: 5, complete: function () {
                        $(".mpb").fadeOut(200, function () {
                            $(this).remove();
                        });
                    }
                });
                div.modal('show', { backdrop: 'static' });
            });
        }

        function CreateState() {

            var div = $("#OpenDilog");
            // div.modal('show', { backdrop: 'static' });
            $.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
            div.load("/StateView/Create", function () {

                $.mpb("update", {
                    value: 100, speed: 5, complete: function () {
                        $(".mpb").fadeOut(200, function () {
                            $(this).remove();
                        });
                    }
                });
                div.modal('show', { backdrop: 'static' });
            }, function (responseText, textStatus, XMLHttpRequest) {

                // XMLHttpRequest.responseText has the error info you want.
                alert(XMLHttpRequest.responseText);
            });
            //$.ajax({
            //    type: 'GET',
            //    url: '/StateView/Create',

            //    success: function (data) {
            //
            //        $("update", {
            //                   value: 100, speed: 5, complete: function () {
            //                       $(".mpb").fadeOut(200, function () {
            //                            $(this).remove();
            //                        });
            //                    }
            //                });
            //        $("#OpenDilog").html(data);
            //        $("#OpenDilog").modal('show', { backdrop: 'static' });
            //    },
            //    error: function (jqXHR, textStatus, errorThrown) {
            //
            //        console.log(textStatus, errorThrown);
            //    }
            //});
        }

        function DeleteState(boardid) {
            if (confirm("Are You Sure to Delete ? ")) {
                $.ajax({
                    url: "/StateView/Delete/" + boardid,
                    type: "post",
                    contentType: "application/json;charset=utf-8",
                    success: function (data) {
                        setTimeout(function () { GetStateJSON() }, 500);
                        //if (data.status) {
                            ModalResponce(data.message, true);
                        //}
                        //else {
                        //    ModalResponce(data.message, false);
                        //}
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }

                });
                

            }
        }

        //?baordId=" + B_ID

    </script>