OzoneUI/Controllers/CountryViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ozone.BAL;
using OzoneUI.Models;
using Ozone.DAL;
using System.Web.Script.Serialization;

namespace OzoneUI.Controllers
{
    public class CountryViewController : Controller
    {
        //
        // GET: /CountryView/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(long countryid = 0)
        {
            if (countryid != null)
            {
                CountryModels country = new CountryModels();
                if (countryid > 0)
                {
                    COUNTRY_MASTER cou = new CountryBAL().GetCountryById(countryid);
                    country.Country_Code = cou.Country_Code;
                    country.Country_Name = cou.Country_Name;
                    country.Pk_Country_Id = cou.Pk_Country_Id;
                    return PartialView(country);
                }
                else
                {
                    return PartialView();
                }
            }
            else
            {
                return PartialView();

            }

        }
        public JsonResult GetCountry(int? start, int length ,string Search)
        {
            int iDisplayStart = start == null ? 0 : start.Value;

            var obj = new CountryBAL().ListCountry(iDisplayStart, length,Search);
            var total = new CountryBAL().GetCountryCount(Search);

            DatatablePaggeing d = new DatatablePaggeing();
            d.aaData = obj;
            d.iTotalDisplayRecords = total;
            d.iTotalRecords = total;
            d.sEcho = "";


            return new JsonResult { Data = d, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public ActionResult Edit(long Countryid)
        {
            return PartialView(new CountryBAL().GetCountryById(Countryid));
        }

        public ContentResult Delete(string id)
        {
            string suc;
            suc = new CountryBAL().DeleteCountry(Convert.ToInt64(id));
            if (suc == "Deleted")
            {
                //return new JsonResult { Data = new { status = true, message = "Product deleted successfully" } };
                return Content("Country deleted successfully", "application/text");
            }
            else
            {
                //return new JsonResult { Data = new { status = false, message = "Oops!! Some error occured" } };
                return Content("Oops!! Some error occured", "application/text");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCountry(CountryBAL country)
        {

            try
            {

                string suc;
                if (new CountryBAL().GetCountryCount(country.Country_Name) > 0)
                {

                    suc = "Exist";
                }
                else
                {
                    if (country.Pk_Country_Id > 0)
                    {
                        country.Modified_By = Convert.ToInt64(Session["UserId"]);
                        suc = new CountryBAL().EditCountry(country);
                    }
                    else
                    {
                        country.Created_by = Convert.ToInt64(Session["UserId"]);
                        suc = CountryBAL.InsertCountry(country);
                    }
                }
                
                if (suc == "Success")
                {
                    return new JsonResult { Data = new { status = true, message = "Country added successfully" } };
                }
                else if (suc == "Updated")
                {
                    return new JsonResult { Data = new { status = true, message = "Country Updated Successfully" } };
                }
                else if( suc=="Exist")
                {
                    return new JsonResult { Data = new { status = false, message = "Country Already Exist" } };
                }
                else
                {
                    return new JsonResult { Data = new { status = false, message = "Try Again!" } };
                }

            }
            catch (Exception e)
            {
                return new JsonResult { Data = new { status = false, message = e.Message } };
            }
        }


    }
}

OzoneUI/Views/CountryView/Create.cshtml
@model OzoneUI.Models.CountryModels

@{
    ViewBag.Title = "Create Country";
}



<div>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Country Master</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">

                        @using (Html.BeginForm("SaveCountry", "CountryView", FormMethod.Post, new { role = "form", id = "saveForm" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="panel-body">

                                @Html.ValidationSummary(true)

                                @Html.HiddenFor(model => model.Pk_Country_Id)




                                <div class="form-group">
                                    @Html.LabelFor(model => model.Country_Name, new { @class = "col-md-4 control-label" })
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.Country_Name, new { @class = "form-control" })
                                        <span class="help-block"> @Html.ValidationMessageFor(model => model.Country_Name)</span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Country_Code, new { @class = "col-md-4 control-label" })
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.Country_Code, new { @class = "form-control" })
                                        <span class="help-block"> @Html.ValidationMessageFor(model => model.Country_Code)</span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-6"></div>
                                    <div class="col-md-6">

                                        <button type="submit" id="savebutton" class="btn btn-info mb-control">Submit</button>
                                    </div>
                                </div>
                            </div>
                        }
                        <div id="msg" style="color:red"></div>

                        @*<div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>*@
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $("#savebutton").button();
    $("body").unbind().on('submit', '#saveForm', function (e) {
        
        e.preventDefault();
        SaveCountry();
    });

    function SaveCountry() {
        $('#savebutton').button('loading');
        

        //Validation
        if ($('#Country_Name').val().trim() == '' ||
            $('#Country_Code').val().trim() == '') {
            $('#msg').html('<div class="failed">All fields are required.</div>');
            $('#savebutton').button('reset');
            return false;
        }

        var Country = {
            Country_Name: $('#Country_Name').val().trim(),
            Country_Code: $('#Country_Code').val().trim(),
            Pk_Country_Id: $('#Pk_Country_Id').val() == '' ? '0' : $('#Pk_Country_Id').val()

        };
        //Add validation token
        Country.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        //Save Contact
        $.ajax({
            url: '/CountryView/SaveCountry',
            type: 'POST',
            data: Country,
            dataType: 'json',
            success: function (data) {
                $('#savebutton').button('reset');
                $('#msg').html('');
                if (data.status) {
                    ModalResponce(data.message, true);
                }
                else {
                    ModalResponce(data.message, false);
                }
                //if (data.status) {
                //    $('#ContactID').val('');
                //    $('#ContactPerson').val('');
                //    $('#ContactNo').val('');
                //    $('#CountryID').val('');
                //    $('#StateID').val('');
                //    LoadContacts();
                //    $dialog.dialog('close');
                //}
            },
            error: function () {
                $('#savebutton').button('reset');
                
                $('#msg').html('<div class="failed">Error! Please try again.</div>');
            }
        });
    }
</script>

OzoneUI/Views/CountryView/Index.cshtml
@model  IEnumerable<Ozone.DAL.COUNTRY_MASTER>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

    @Scripts.Render("~/bundles/notify")

    @*<ul class="breadcrumb">
        <li><a href="#">Home</a></li>

        <li class="active">Country</li>
        <li>Welcome : <label id="lblUser"></label></li>

    </ul>*@


    <!-- PAGE TITLE -->
    <!-- END PAGE TITLE -->
    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12"><br />
                <p>
                    <input type="button" class="btn btn-info mb-control" value="Add new Country" onclick="CreateCountry()" />
                   
                </p>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">List of Country</h3>
                        <ul class="panel-controls">

                            <li><input id="txtSeach" type="text" class="form-control" name="name" value="" onchange="SearchText(this.value);" placeholder="Search... " /></li>
                        </ul>
                        @*<ul class="panel-controls">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                        </ul>*@
                    </div>
                    <div id='OpenDilog' class="modal"  tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">

                    </div>

                    <div class="panel-body">
                        <table id="Country" class="table ">
                            <thead><tr><th>Country</th><th>Country Code</th><th>Action</th></tr></thead>
                            <tbody></tbody>
                          </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#lblUserId').text(@Request.QueryString["id"]);
            GetCountryJSON();
        });

        function GetCountryJSON() {
            $('#Country').dataTable({
                "bDestroy": true
            }).fnDestroy();
            var search = $('#txtSeach').val();
            window.table = $('#Country').DataTable({                
                "bSort": false,
                "processing": true,
                "serverSide": true,
                'searching': false,
                'language': {
                    "processing": "<img src='../img/loaders/default.gif' />" //add a loading image,simply putting <img src="loader.gif" /> tag.
                },
                "ajax": "/CountryView/GetCountry?Search=" + search,
                "columns": [
                    { "data": "Country_Name" },
                    { "data": "Country_Code" },                   
                    { "data": "" }

                ],
                "columnDefs": [{
                    "targets": -1,
                    "data": null,
                    "defaultContent": "<button id='edt' class='btn btn-default btn-rounded btn-sm' ><span class='fa fa-pencil'></span></button>&nbsp;&nbsp;<button style='display:none' id='del' class='btn btn-default btn-rounded btn-sm edit'><span class='fa fa-times'></span></button>"
                }],
                "bDestroy": true


            });
            $('#Country th:first').removeClass('sorting_asc');
            $('#Country tbody').unbind().on('click', 'button', function () {

                var data = window.table.row($(this).parents('tr')).data();
                if ($(this).attr('id') == 'edt') {
                    
                    EditCountry(data.Pk_Country_Id);
                }
                if ($(this).attr('id') == 'del') {
                    DeleteCountry(data.Pk_Country_Id);
                }


            });
        }
        $(".panel-refresh").on("click", function () {
            window.table.ajax.reload();
        });
        function ModalResponce(data, suc) {

            if (suc) {
                $("#OpenDilog").modal('hide');
                noty({ text: data, layout: 'topRight', type: 'success' }).setTimeout(3000);;

            }
            else {
                debugger;
                $("#OpenDilog").modal('hide');
                noty({ text: data, layout: 'topRight', type: 'error' }).setTimeout(3000);;
            }
            window.table.ajax.reload();
        }
        function EditCountry(B_ID) {
            
            var div = $("#OpenDilog");
            $.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
            div.load("/CountryView/Create?countryid=" + B_ID, function () {
                $.mpb("update", {
                    value: 100, speed: 5, complete: function () {
                        $(".mpb").fadeOut(200, function () {
                            $(this).remove();
                        });
                    }
                });
                div.modal('show', { backdrop: 'static' });
            });
        }

        function CreateCountry() {
            
            var div = $("#OpenDilog");
           // div.modal('show', { backdrop: 'static' });
            $.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
            div.load("/CountryView/Create", function () {
                
                $.mpb("update", {
                    value: 100, speed: 5, complete: function () {
                        $(".mpb").fadeOut(200, function () {
                            $(this).remove();
                        });
                    }
                });
                div.modal('show', { backdrop: 'static' });
            }, function (responseText, textStatus, XMLHttpRequest) {
                
                // XMLHttpRequest.responseText has the error info you want.
                alert(XMLHttpRequest.responseText);
            });
            //$.ajax({
            //    type: 'GET',
            //    url: '/CountryView/Create',

            //    success: function (data) {
            //        
            //        $("update", {
            //                   value: 100, speed: 5, complete: function () {
            //                       $(".mpb").fadeOut(200, function () {
            //                            $(this).remove();
            //                        });
            //                    }
            //                });
            //        $("#OpenDilog").html(data);
            //        $("#OpenDilog").modal('show', { backdrop: 'static' });
            //    },
            //    error: function (jqXHR, textStatus, errorThrown) {
            //        
            //        console.log(textStatus, errorThrown);
            //    }
            //});
        }

        function DeleteCountry(boardid) {
            if (confirm("Are You Sure to Delete ? ")) {
                $.ajax({
                    url: "/CountryView/Delete/" + boardid,
                    type: "post",
                    contentType: "application/json;charset=utf-8",
                    success: function (data) {
                        setTimeout(function () { GetCountryJSON() }, 500);
                        //if (data.status) {
                            ModalResponce(data, true);
                        //}
                        //else {
                        //    ModalResponce(data.message, false);
                        //}
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }

                });
               

            }
        }
        function SearchText(srch) {
            GetCountryJSON();
        }
        //?baordId=" + B_ID

    </script>

    